export const cityList = [
  "sthlm", "Marstrand", "Göteborg", "Mölnlycke", "Marstrand", "Hägersten", "Stocksund", "Utö", "Skärholmen", "Nynäshamn", "Johanneshov", "Nybrokajen", 
  "Gothenburg","Kungsbacka","Särö","Nösund","Säve","Askim","Västra Frölunda","Kungälv","Hisings Backa","Västerås","Katrineholm","Torshälla","Mölndal","Vidsel","Sigtuna","Uppsala","Köping","Kungsör","Enköping","Knivsta","Stockholm-Arlanda","Ramnäs","Hallstahammar","Örebro","Malmköping","Malung","Umeå","Grebbestad","Stockholm","Bromma","Bro","Malmö","Nykvarn","Arlandastad","Kista","Mörkö","Norrköping","Älvsjö","Spånga","Sollentuna","Rosersberg","Vällingby","Örsundsbro","Grödinge","Ekerö","Södertälje","Mariefred","Kungens Kurva","Märsta","Sundbyberg","Bålsta","Gävle","Borlänge","Fiskebäckskil","Lerum","Härryda","Nyköping","Ösmo","Oxelösund","Nacka","Ludvika","Örnsköldsvik","Skellefteå","Genarp","Degeberga","Smygehamn","Lund","Ystad","Hemavan","Borås","Gränna","Grundsund","Smögen","Lysekil","Uddevalla","Brastad","Helsingborg","Landskrona","Eslöv","Sundsvall","Härnösand","Trollhättan","Vänersborg","Motala","Linköping","Värnamo","Lidingö","Djurhamn","Åkersberga","Norrtälje","Danderyd","Halmstad","Solna","Östersund","Kivik","Simrishamn","Kristianstad","Bromölla","Hässleholm","Karlskoga","Kiruna","Åre","Kalmar","Ängelholm","Ljungbyhed","Båstad","Vejbystrand","Falkenberg","Varberg","Hillerstorp","Hestra","Hindås","Sollefteå","Luleå","Hammerdal","Karlskrona","Ronneby","Tällberg","Västerlanda","Henån","Alfta","Falköping","Sydkoster","Sjöbo","Åhus","Yngsjö","Brokind","Hultsfred","Oskarshamn","Skara","Charlottenberg","Jönköping","Aneby","Huskvarna","Tranås","Askersund","Vetlanda","Hok","Lannavaara","Karlshamn","Älmhult","Lidköping","Kumla","Skövde","Björkliden","Kalix","Mörbylånga","Höör","Karlsborg","Åby","Hyssna","Örby","Funäsdalen","Moholm","Sunne","Laholm","Skummeslövsstrand","Markaryd",
  
]

export const supplementCityList = [
  'Suttungs gränd',      'Körsbärsvägen',       'Vanadisvägen',
  'Eugeniavägen',        'Stockholm Arlanda',   'Sturegatan',
  'Birger Jarlsgatan',   'Karlsbodavägen',      'Ulvsundavägen',
  'Nybrokajen',          'Norrbyvägen',         'Saltsjöqvarns kaj',
  'Kyrkogatan',          'Strängnäs',           'Stora Torget',
  'Avesta',              'Hamngatan',           'Katrineholm',
  'Orebro',              'Tällgårdsgattu',      'Fabriksgatan',
  'TYSKA TORGET',        'Mora',                'Karlskoga',
  'Linköping',           'Storgatan',           'Norrmalmstorg',
  'Torsgatan 10',        'Klarabergsviadukten', 'Skeppsbron',
  'Cederströms Slinga',  'Uppsala',             'Tornvägen 2',
  'Taby',                'Djursholmsvägen',     'Lidingö',
  'Bålsta',              'Isafjordsgatan',      'Franckes väg',
  'Bro',                 'Råsta Strandväg',     'Sandhamnsgatan',
  'Jungfrugatan',        'Råsundavägen',        'Hälsingegatan 49',
  'Solnavägen',          'Snickarbacken',       'Grev Turegatan',
  'Holländargatan 17',   'Riddargatan',         'Malmskillnadsgatan',
  'Östra Järnvägsgatan', 'Vasagatan',           'Kungsgatan',
  'Vasaplan',            'Djurgårdsslätten',    'Djurgårdsvägen',
  'Gröna gången',        'Sandhamn',            'Kungsholmsgatan',
  'Kastellbacken',       'Ferkens Gränd',       'Lindhagensgatan',
  'Margretelundsvägen',  'Maltesholmsvägen',    'Maria',
  'Gustavslundsvägen',   'Saltsjobaden',        'Maria Bangata',
  'Bromma',              'Åkeshovs gårdsväg',   'Kanaans väg',
  'Johanneshov',         'Arenavägen',          'Hägersten',
  'Gävle',               'Skarholmen',          'Huddinge',
  'Sodertaljie',         'Södertälje',          'Västerås',
  'Ösmo',                'Telegrafgatan',       'Munktellstorget',
  'Eskilstuna',          'Falun',               'Nykoeping',
  'Nyköping',            'Nykoping',            'Borlänge',
  'Ludvika',             'Hudiksvall',          'Örebro',
  'Tallberg',            'Norrköping',          'Finspång',
  'Linkoping',           'Klostergatan',        'Sundsvall',
  'Esplanaden',          'Motala',              'Visby',
  'Strandgatan',
]